apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod

resources:
  - namespace.yaml
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

patches:
  - patch: |-
      - op: replace
        path: "/metadata/namespace"
        value: "clouds-api-prod"    
    target:
      name: .*
