apiVersion: v1
kind: Service
metadata:
  labels:
    app: articles-api
  name: articles-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: articles-api